### ISSUE TITLE
[question] Difference between this plugin and vitality?

### ISSUE THREAD

**Issue by ddickstein** [tmux-plugins/vim-tmux-focus-events#13]
In your README you credit [Vitality.vim](https://github.com/sjl/vitality.vim/) for much of the code, and when I checked out that plugin it looks like it is trying to do something similar.  What's the difference between the two plugins?

**Comment by bruno-** [comment]
As the readme states, the big chunk of code was taken from vitality vim.

- I removed vitality's code for changing vim's cursor when in insert mode as I couldn't get this one to work in my terminal and is not core to the plugin
- Added logic to support vim's `autoread` option. Enabling this one propted me to investigate and search for options.. that is how I discovered vitality in the first place.

There may be some other details.

**Comment by bruno-** [comment]
Please reopen if more info is needed.
