### ISSUE TITLE
Modelines are re-executed when focus is lost/gained

### ISSUE THREAD

**Issue by keysmashes** [tmux-plugins/vim-tmux-focus-events#14]
Whenever a terminal running tmux & vim loses focus, any modelines get re-executed. This wouldn't be a problem, except that my .vimrc's modeline contains `set foldlevel=0`, so every time I alt-tab to another window, all my folds get closed. I've tested with a fairly minimal .vimrc, and I don't think this is being caused by any other plugin; it also doesn't happen outside of tmux.

To reproduce: have this .vimrc, open it, observe that you can open and close the fold with `za`, and if you alt-tab with the fold open, it stays open. Then, add the line `" vim: set foldlevel=0:` to the end of the .vimrc (no need to save), open the fold, alt-tab, and see that the fold closes.

.vimrc:

```
set nocompatible

" Plugins {{{1

call plug#begin()
Plug 'tmux-plugins/vim-tmux-focus-events'
call plug#end()

" }}}

set bg=dark

set foldenable
set foldmethod=marker

set modeline
set modelines=5
```

**Comment by bruno-** [comment]
Thanks for reporting. From what I can see #8 resolves this.

**Comment by bruno-** [comment]
Changes in PR #8 have been merged to master. That should fix this issue. Let me know if you still have problems.
