### ISSUE TITLE
Error when opening command history and losing focus

### ISSUE THREAD

**Issue by simonsmith** [tmux-plugins/vim-tmux-focus-events#3]
Hi,

If I open command history `q:` and switch to a different app when I come back to iTerm I get the following error:

![screen shot 2015-09-14 at 10 51 04](https://cloud.githubusercontent.com/assets/360703/9847108/a458cbb8-5ace-11e5-92c9-0189bf483ff2.png)

I'm running tmux and vim in iTerm. My vimrc is here - https://github.com/simonsmith/dotfiles/blob/master/.vimrc

Thanks for any help!

**Comment by bruno-** [comment]
Hey, #11 solves this issue and it was just merged.
