### ISSUE TITLE
Is this plugin still necessary for neovim

### ISSUE THREAD

**Issue by lewis6991** [tmux-plugins/vim-tmux-focus-events#38]
On the README there is a link to this old [vim patch](https://groups.google.com/forum/#!topic/vim_dev/ASn8QqQqVe0) about adding tmux focus reporting natively.

I took a look at the change to see if it could be applied to neovim and found neovim now uses a completely different implementation for its TUI.

Anyway I've tried uninstalling this plugin and as far as I can tell focus reporting works fine in neovim.

If someone else can confirm we should update the README and probably simplify the plugin by removing any neovim specific code (if there is any).

Thanks.

**Comment by bruno-** [comment]
As far as I remember there's no neovim specific code in this plugin.
But yea, we should update the README if neovim doesn't need this plugin.

**Comment by przepompownia** [comment]
Indeed, on neovim inside tmux this plugin is unneeded. After removing it I noticed that on [nvim-qt](https://github.com/equalsraf/neovim-qt.git) I have to run `:checktime` manually again or restore `call tmux_focus_events#focus_gained()` after `FocusGained` was triggered.
