### ISSUE TITLE
nevoid error for `autocommands for ALL events`

### ISSUE THREAD

**Issue by vitaly** [tmux-plugins/vim-tmux-focus-events#40]
https://github.com/tmux-plugins/vim-tmux-focus-events/blob/b1330e04ffb95ede8e02b2f7df1f238190c67056/autoload/tmux_focus_events.vim#L35

If I open vim and quickly start command mode, I get the following error:
~~~
Error detected while processing function tmux_focus_events#focus_gained:
line    8:
E1155: Cannot define autocommands for ALL events
~~~

**Comment by bruno-** [comment]
Hey, check the readme, this plugin is now obsolete.
